name: '🐞 Swiper Core Issue'
description: Report an issue with Swiper
labels: []
body:
  - type: markdown
    attributes:
      value: |
        Thanks for taking the time to fill out this bug report!
  - type: checkboxes
    id: qa
    attributes:
      label: Check that this is really a bug
      description: For Q&A open a [GitHub Discussion](https://github.com/nolimits4web/swiper/discussions) or join our [Discord Chat Server](https://discord.gg/BUpd4UTkgj)
      options:
        - label: I confirm
          required: true
  - type: input
    id: reproduction
    attributes:
      label: Reproduction link
      description: Please provide a link to a repo that can reproduce the problem you ran into. You can fork one of our [demos](https://swiperjs.com/demos) in codesandbox to get start. A reproduction is required unless you are absolutely sure that the issue is obvious and the provided information is enough to understand the problem. If a report is vague (e.g. just a generic error message) and has no reproduction, it will receive a "missing demo" label. If no reproduction is provided after 3 days, it will be auto-closed.
      placeholder: 'https://codesandbox.io/..'
    validations:
      required: true
  - type: textarea
    id: descr
    attributes:
      label: Bug description
      description: A clear and concise description of what the bug is
    validations:
      required: true
  - type: textarea
    id: expected
    attributes:
      label: Expected Behavior
      description: A concise description of what you're experiencing
    validations:
      required: false
  - type: textarea
    id: actual
    attributes:
      label: Actual Behavior
      description: A concise description of what you expected to happen.
    validations:
      required: false
  - type: input
    id: swiper
    attributes:
      label: Swiper version
      description: Exact release version or commit hash
      placeholder: e.g 6.7.1
    validations:
      required: true
  - type: input
    id: browser
    attributes:
      label: Platform/Target and Browser Versions
      description: Platform client you are targeting such as macOS, Windows, Cordova, iOS, Android, Chrome, etc.
      placeholder: e.g macOS Safari 14.1
    validations:
      required: true
  - type: checkboxes
    id: checkboxes
    attributes:
      label: Validations
      description: Before submitting the issue, please make sure you do the following
      options:
        - label: Follow our [Code of Conduct](https://github.com/nolimits4web/swiper/blob/master/CODE_OF_CONDUCT.md)
          required: true
        - label: Read the [docs](https://swiperjs.com/swiper-api).
          required: true
        - label: Check that there isn't already an issue that request the same feature to avoid creating a duplicate.
          required: true
        - label: Make sure this is a Swiper issue and not a framework-specific issue
          required: true
  - type: checkboxes
    id: pr
    attributes:
      label: Would you like to open a PR for this bug?
      description: Before starting to work on PR it is recommended to get maintainers approval
      options:
        - label: I'm willing to open a PR
          required: false
